// "use client"; // Client Component
import Link from "next/link";
// import { useEffect, useState } from 'react' // Client Component
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Web tutorials',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Client Component
  // export default function RootLayout({
  // const [topics, setTopics] = useState<string[]>([]);
  // useEffect(() => {
  //   fetch('http://localhost:9999/topics')
  //   .then(res => res.json())
  //   .then(result => {
  //     setTopics(result);
  //   });
  // },[]);

  // Server Component
  // export default async function RootLayout({
  const res = await fetch('http://localhost:9999/topics', { cache: 'no-store' });
  const topics = await res.json();

  return (
    <html>
      <body>
        <h1><Link href='/'>WEB</Link></h1>
        <ol>
          {topics.map((t:any) => {
            return <li key={t.id}><Link href={`/read/${t.id}`}>{t.title}</Link></li>
          })}
        </ol>
        {children}
        <ul>
          <li><Link href='/create'>Create</Link></li>
          <li><Link href='/update'>Update</Link></li>
          <li><input type='button' value='delete'/></li>
        </ul>
      </body>
    </html>
  )
}
